-- demo-seed.golden.sql — CHECKED-IN EXPECTED OUTPUT of buildSeedSql(SCENARIOS,
-- 'coach@example.com', 2026-07-22T12:00:00.000Z). Not applied to any database, ever.
--
-- REGENERATING THIS FILE IS A DECISION, NOT A CHORE.
--
-- This is the script the repo owner pastes into the Supabase SQL editor against
-- PRODUCTION, with the dates and the coach email swapped for a real run. A diff
-- here is a diff in that script. Read it line by line and be able to say, for
-- every changed line, what it does to a production refresh — a reordered
-- statement, a dropped column, a widened DELETE and a swapped VALUES position
-- all look like ordinary churn in a diff and are none of them ordinary.
--
-- Do NOT re-record it to make a red test green. Re-record it only after you
-- have read the change and decided the new output is the one you want:
--
--   cd web && npx tsx scripts/seed/golden-seed.ts
--
-- This file pins the ARTIFACT. The invariants it cannot state on its own —
-- best_lap = min of the session's laps, laps belonging to the right session,
-- day INSERTs preceding the sessions that reference them — are asserted
-- separately in src/lib/__tests__/generate-demo-seed.test.ts. Both are load
-- bearing; neither replaces the other.
--
-- ==== generated output begins below this line ====
BEGIN;
-- demo-seed.sql — GENERATED by scripts/seed/generate-demo-seed.ts
-- Generated: 2026-07-22T12:00:00.000Z  Coach: coach@example.com
-- Idempotent: re-run any time to refresh demo dates. Do not edit by hand.
DO $seed_guard$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM coaches WHERE email = 'coach@example.com') THEN
    RAISE EXCEPTION 'Coach % not found — check coaches.email', 'coach@example.com';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM tracks WHERE name = 'Thunderhill Raceway') THEN
    RAISE EXCEPTION 'Track % not found — check tracks.name', 'Thunderhill Raceway';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM tracks WHERE name = 'Sonoma Raceway') THEN
    RAISE EXCEPTION 'Track % not found — check tracks.name', 'Sonoma Raceway';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM tracks WHERE name = 'Buttonwillow Raceway') THEN
    RAISE EXCEPTION 'Track % not found — check tracks.name', 'Buttonwillow Raceway';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM tracks WHERE name = 'Laguna Seca') THEN
    RAISE EXCEPTION 'Track % not found — check tracks.name', 'Laguna Seca';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM tracks WHERE name = 'Streets of Willow') THEN
    RAISE EXCEPTION 'Track % not found — check tracks.name', 'Streets of Willow';
  END IF;
END $seed_guard$;

DELETE FROM focus_items WHERE driver_id IN ('dd000000-0000-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000006');
UPDATE sessions SET track_day_id = NULL WHERE driver_id IN ('dd000000-0000-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000006');
DELETE FROM track_days WHERE driver_id IN ('dd000000-0000-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000006');
DELETE FROM laps WHERE session_id IN (
  SELECT id FROM sessions WHERE driver_id IN ('dd000000-0000-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000006')
    AND id NOT IN ('dd000000-0001-4000-a000-000000000001', 'dd000000-0001-4000-a000-000000000002', 'dd000000-0001-4000-a000-000000000003', 'dd000000-0001-4000-a000-000000000004', 'dd000000-0001-4000-a000-000000000005', 'dd000000-0001-4000-a000-000000000006', 'dd000000-0001-4000-a000-000000000007', 'dd000000-0001-4000-a000-000000000008', 'dd000000-0002-4000-a000-000000000001', 'dd000000-0002-4000-a000-000000000002', 'dd000000-0002-4000-a000-000000000003', 'dd000000-0003-4000-a000-000000000001', 'dd000000-0003-4000-a000-000000000002', 'dd000000-0003-4000-a000-000000000003', 'dd000000-0003-4000-a000-000000000004', 'dd000000-0003-4000-a000-000000000005', 'dd000000-0004-4000-a000-000000000001', 'dd000000-0004-4000-a000-000000000002', 'dd000000-0004-4000-a000-000000000003', 'dd000000-0004-4000-a000-000000000004', 'dd000000-0004-4000-a000-000000000005', 'dd000000-0004-4000-a000-000000000006', 'dd000000-0004-4000-a000-000000000007', 'dd000000-0004-4000-a000-000000000008', 'dd000000-0004-4000-a000-000000000009', 'dd000000-0004-4000-a000-000000000010', 'dd000000-0004-4000-a000-000000000011', 'dd000000-0004-4000-a000-000000000012', 'dd000000-0005-4000-a000-000000000001', 'dd000000-0005-4000-a000-000000000002', 'dd000000-0006-4000-a000-000000000001', 'dd000000-0006-4000-a000-000000000002', 'dd000000-0006-4000-a000-000000000003', 'dd000000-0006-4000-a000-000000000004', 'dd000000-0006-4000-a000-000000000005', 'dd000000-0006-4000-a000-000000000006')
);
DELETE FROM sessions WHERE driver_id IN ('dd000000-0000-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000006')
  AND id NOT IN ('dd000000-0001-4000-a000-000000000001', 'dd000000-0001-4000-a000-000000000002', 'dd000000-0001-4000-a000-000000000003', 'dd000000-0001-4000-a000-000000000004', 'dd000000-0001-4000-a000-000000000005', 'dd000000-0001-4000-a000-000000000006', 'dd000000-0001-4000-a000-000000000007', 'dd000000-0001-4000-a000-000000000008', 'dd000000-0002-4000-a000-000000000001', 'dd000000-0002-4000-a000-000000000002', 'dd000000-0002-4000-a000-000000000003', 'dd000000-0003-4000-a000-000000000001', 'dd000000-0003-4000-a000-000000000002', 'dd000000-0003-4000-a000-000000000003', 'dd000000-0003-4000-a000-000000000004', 'dd000000-0003-4000-a000-000000000005', 'dd000000-0004-4000-a000-000000000001', 'dd000000-0004-4000-a000-000000000002', 'dd000000-0004-4000-a000-000000000003', 'dd000000-0004-4000-a000-000000000004', 'dd000000-0004-4000-a000-000000000005', 'dd000000-0004-4000-a000-000000000006', 'dd000000-0004-4000-a000-000000000007', 'dd000000-0004-4000-a000-000000000008', 'dd000000-0004-4000-a000-000000000009', 'dd000000-0004-4000-a000-000000000010', 'dd000000-0004-4000-a000-000000000011', 'dd000000-0004-4000-a000-000000000012', 'dd000000-0005-4000-a000-000000000001', 'dd000000-0005-4000-a000-000000000002', 'dd000000-0006-4000-a000-000000000001', 'dd000000-0006-4000-a000-000000000002', 'dd000000-0006-4000-a000-000000000003', 'dd000000-0006-4000-a000-000000000004', 'dd000000-0006-4000-a000-000000000005', 'dd000000-0006-4000-a000-000000000006');

-- track_days below are PLAIN INSERTs with NO ON CONFLICT, deliberately.
-- The wholesale delete above guarantees a clean slate, so a collision here
-- is a real bug and must abort the transaction loudly. This is NOT the
-- import route's keys-only ON CONFLICT upsert and must not be made to
-- resemble it: that one protects coach-authored day notes on a re-import,
-- this one is a seed rebuilding rows it just deleted.

-- Kai Garcia (faded) — 2 day(s), 8 session(s)
INSERT INTO drivers (id, name, email, coach_id, created_at) VALUES ('dd000000-0000-4000-a000-000000000001', 'Kai Garcia', 'kai.garcia@trackapp.demo', (SELECT id FROM coaches WHERE email = 'coach@example.com'), now()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, coach_id = EXCLUDED.coach_id;
INSERT INTO driver_profiles (driver_id, experience_level, total_sessions) VALUES ('dd000000-0000-4000-a000-000000000001', 'beginner', 8) ON CONFLICT (driver_id) DO UPDATE SET experience_level = EXCLUDED.experience_level, total_sessions = EXCLUDED.total_sessions;
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0001-4000-b000-000000000001', 'dd000000-0000-4000-a000-000000000001', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-11', NULL);
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0001-4000-b000-000000000002', 'dd000000-0000-4000-a000-000000000001', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-18', 'Hot day, 95F by lunch. Kai on the same set of tires all day.');
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0001-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000001', 'dd000000-0001-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-11T17:00:00.000Z', 736600, 91900, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0001-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000001', 'dd000000-0001-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-11T19:00:00.000Z', 735500, 91500, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0001-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000001', 'dd000000-0001-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-11T21:00:00.000Z', 735200, 91400, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0001-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000001', 'dd000000-0001-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-11T23:00:00.000Z', 735500, 91700, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0001-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000001', 'dd000000-0001-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-18T17:00:00.000Z', 734650, 91450, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0001-4000-a000-000000000006', 'dd000000-0000-4000-a000-000000000001', 'dd000000-0001-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-18T19:00:00.000Z', 734400, 91600, 'manual', 'not_representative', 'Instructor ride-along — demo laps, not a timed run.') ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0001-4000-a000-000000000007', 'dd000000-0000-4000-a000-000000000001', 'dd000000-0001-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-18T21:00:00.000Z', 733750, 91300, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0001-4000-a000-000000000008', 'dd000000-0000-4000-a000-000000000001', 'dd000000-0001-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-18T23:00:00.000Z', 825650, 91300, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;

-- Marcus Webb (regressed) — 2 day(s), 3 session(s)
INSERT INTO drivers (id, name, email, coach_id, created_at) VALUES ('dd000000-0000-4000-a000-000000000002', 'Marcus Webb', 'marcus.webb@trackapp.demo', (SELECT id FROM coaches WHERE email = 'coach@example.com'), now()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, coach_id = EXCLUDED.coach_id;
INSERT INTO driver_profiles (driver_id, experience_level, total_sessions) VALUES ('dd000000-0000-4000-a000-000000000002', 'intermediate', 3) ON CONFLICT (driver_id) DO UPDATE SET experience_level = EXCLUDED.experience_level, total_sessions = EXCLUDED.total_sessions;
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0002-4000-b000-000000000001', 'dd000000-0000-4000-a000-000000000002', (SELECT id FROM tracks WHERE name = 'Sonoma Raceway'), '2026-07-12', NULL);
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0002-4000-b000-000000000002', 'dd000000-0000-4000-a000-000000000002', (SELECT id FROM tracks WHERE name = 'Sonoma Raceway'), '2026-07-19', 'Second event back after the gearbox rebuild. Watch turn 7 entry.');
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0002-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000002', 'dd000000-0002-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Sonoma Raceway'), '2026-07-12T17:00:00.000Z', 718700, 89400, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0002-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000002', 'dd000000-0002-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Sonoma Raceway'), '2026-07-19T17:00:00.000Z', 725900, 90500, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0002-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000002', 'dd000000-0002-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Sonoma Raceway'), '2026-07-19T21:00:00.000Z', 726700, 90600, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;

-- Ava Torres (off_baseline) — 2 day(s), 5 session(s)
INSERT INTO drivers (id, name, email, coach_id, created_at) VALUES ('dd000000-0000-4000-a000-000000000003', 'Ava Torres', 'ava.torres@trackapp.demo', (SELECT id FROM coaches WHERE email = 'coach@example.com'), now()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, coach_id = EXCLUDED.coach_id;
INSERT INTO driver_profiles (driver_id, experience_level, total_sessions) VALUES ('dd000000-0000-4000-a000-000000000003', 'intermediate', 5) ON CONFLICT (driver_id) DO UPDATE SET experience_level = EXCLUDED.experience_level, total_sessions = EXCLUDED.total_sessions;
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0003-4000-b000-000000000001', 'dd000000-0000-4000-a000-000000000003', (SELECT id FROM tracks WHERE name = 'Buttonwillow Raceway'), '2026-07-12', NULL);
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0003-4000-b000-000000000002', 'dd000000-0000-4000-a000-000000000003', (SELECT id FROM tracks WHERE name = 'Buttonwillow Raceway'), '2026-07-19', 'New tires on in the afternoon. Ava chasing the fast lap, not the rhythm.');
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0003-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0003-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Buttonwillow Raceway'), '2026-07-12T17:00:00.000Z', 764000, 95250, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0003-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0003-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Buttonwillow Raceway'), '2026-07-12T19:00:00.000Z', 763600, 95200, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0003-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0003-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Buttonwillow Raceway'), '2026-07-12T21:00:00.000Z', 764400, 95300, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0003-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0003-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Buttonwillow Raceway'), '2026-07-19T17:00:00.000Z', 763200, 95150, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0003-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000003', 'dd000000-0003-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Buttonwillow Raceway'), '2026-07-19T21:00:00.000Z', 763800, 94800, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;

-- Elena Ross (ready) — 3 day(s), 12 session(s)
INSERT INTO drivers (id, name, email, coach_id, created_at) VALUES ('dd000000-0000-4000-a000-000000000004', 'Elena Ross', 'elena.ross@trackapp.demo', (SELECT id FROM coaches WHERE email = 'coach@example.com'), now()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, coach_id = EXCLUDED.coach_id;
INSERT INTO driver_profiles (driver_id, experience_level, total_sessions) VALUES ('dd000000-0000-4000-a000-000000000004', 'advanced', 12) ON CONFLICT (driver_id) DO UPDATE SET experience_level = EXCLUDED.experience_level, total_sessions = EXCLUDED.total_sessions;
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0004-4000-b000-000000000001', 'dd000000-0000-4000-a000-000000000004', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-04', NULL);
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0004-4000-b000-000000000002', 'dd000000-0000-4000-a000-000000000004', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-18', NULL);
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0004-4000-b000-000000000003', 'dd000000-0000-4000-a000-000000000004', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-19', 'Sunday of the doubleheader. Elena finally stopped chasing the entry to 2.');
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-04T17:00:00.000Z', 719000, 89400, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-04T19:00:00.000Z', 717650, 89150, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-04T21:00:00.000Z', 714500, 88900, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-04T23:00:00.000Z', 713350, 88700, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-18T17:00:00.000Z', 711400, 88450, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000006', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-18T19:00:00.000Z', 709400, 88200, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000007', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-18T21:00:00.000Z', 707300, 88000, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000008', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-18T23:00:00.000Z', 706450, 87750, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000009', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000003', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-19T17:00:00.000Z', 703800, 87500, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000010', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000003', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-19T19:00:00.000Z', 701300, 87250, 'manual', 'partial', 'Full-course yellow at four minutes — session cut short.') ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000011', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000003', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-19T21:00:00.000Z', 699800, 87000, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0004-4000-a000-000000000012', 'dd000000-0000-4000-a000-000000000004', 'dd000000-0004-4000-b000-000000000003', (SELECT id FROM tracks WHERE name = 'Laguna Seca'), '2026-07-19T23:00:00.000Z', 696120, 86700, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;

-- Jordan Lee (building) — 1 day(s), 2 session(s)
INSERT INTO drivers (id, name, email, coach_id, created_at) VALUES ('dd000000-0000-4000-a000-000000000005', 'Jordan Lee', 'jordan.lee@trackapp.demo', (SELECT id FROM coaches WHERE email = 'coach@example.com'), now()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, coach_id = EXCLUDED.coach_id;
INSERT INTO driver_profiles (driver_id, experience_level, total_sessions) VALUES ('dd000000-0000-4000-a000-000000000005', 'beginner', 2) ON CONFLICT (driver_id) DO UPDATE SET experience_level = EXCLUDED.experience_level, total_sessions = EXCLUDED.total_sessions;
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0005-4000-b000-000000000001', 'dd000000-0000-4000-a000-000000000005', (SELECT id FROM tracks WHERE name = 'Streets of Willow'), '2026-07-18', NULL);
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0005-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000005', 'dd000000-0005-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Streets of Willow'), '2026-07-18T17:00:00.000Z', 490100, 97600, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0005-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000005', 'dd000000-0005-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Streets of Willow'), '2026-07-18T19:00:00.000Z', 390500, 97400, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;

-- Sam Whitaker (ok) — 3 day(s), 6 session(s)
INSERT INTO drivers (id, name, email, coach_id, created_at) VALUES ('dd000000-0000-4000-a000-000000000006', 'Sam Whitaker', 'sam.whitaker@trackapp.demo', (SELECT id FROM coaches WHERE email = 'coach@example.com'), now()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, coach_id = EXCLUDED.coach_id;
INSERT INTO driver_profiles (driver_id, experience_level, total_sessions) VALUES ('dd000000-0000-4000-a000-000000000006', 'advanced', 6) ON CONFLICT (driver_id) DO UPDATE SET experience_level = EXCLUDED.experience_level, total_sessions = EXCLUDED.total_sessions;
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0006-4000-b000-000000000001', 'dd000000-0000-4000-a000-000000000006', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-05', NULL);
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0006-4000-b000-000000000002', 'dd000000-0000-4000-a000-000000000006', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-12', NULL);
INSERT INTO track_days (id, driver_id, track_id, date, notes) VALUES ('dd000000-0006-4000-b000-000000000003', 'dd000000-0000-4000-a000-000000000006', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-19', NULL);
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0006-4000-a000-000000000001', 'dd000000-0000-4000-a000-000000000006', 'dd000000-0006-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-05T17:00:00.000Z', 723200, 90150, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0006-4000-a000-000000000002', 'dd000000-0000-4000-a000-000000000006', 'dd000000-0006-4000-b000-000000000001', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-05T21:00:00.000Z', 722000, 89900, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0006-4000-a000-000000000003', 'dd000000-0000-4000-a000-000000000006', 'dd000000-0006-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-12T17:00:00.000Z', 723200, 90000, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0006-4000-a000-000000000004', 'dd000000-0000-4000-a000-000000000006', 'dd000000-0006-4000-b000-000000000002', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-12T21:00:00.000Z', 723200, 89950, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0006-4000-a000-000000000005', 'dd000000-0000-4000-a000-000000000006', 'dd000000-0006-4000-b000-000000000003', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-19T17:00:00.000Z', 724000, 89950, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;
INSERT INTO sessions (id, driver_id, track_day_id, track_id, date, total_time_ms, best_lap_ms, source, representativeness, representativeness_note) VALUES ('dd000000-0006-4000-a000-000000000006', 'dd000000-0000-4000-a000-000000000006', 'dd000000-0006-4000-b000-000000000003', (SELECT id FROM tracks WHERE name = 'Thunderhill Raceway'), '2026-07-19T21:00:00.000Z', 724000, 90150, 'manual', NULL, NULL) ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_day_id = EXCLUDED.track_day_id, track_id = EXCLUDED.track_id, date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms, representativeness = EXCLUDED.representativeness, representativeness_note = EXCLUDED.representativeness_note;

DELETE FROM laps WHERE session_id IN ('dd000000-0001-4000-a000-000000000001', 'dd000000-0001-4000-a000-000000000002', 'dd000000-0001-4000-a000-000000000003', 'dd000000-0001-4000-a000-000000000004', 'dd000000-0001-4000-a000-000000000005', 'dd000000-0001-4000-a000-000000000006', 'dd000000-0001-4000-a000-000000000007', 'dd000000-0001-4000-a000-000000000008', 'dd000000-0002-4000-a000-000000000001', 'dd000000-0002-4000-a000-000000000002', 'dd000000-0002-4000-a000-000000000003', 'dd000000-0003-4000-a000-000000000001', 'dd000000-0003-4000-a000-000000000002', 'dd000000-0003-4000-a000-000000000003', 'dd000000-0003-4000-a000-000000000004', 'dd000000-0003-4000-a000-000000000005', 'dd000000-0004-4000-a000-000000000001', 'dd000000-0004-4000-a000-000000000002', 'dd000000-0004-4000-a000-000000000003', 'dd000000-0004-4000-a000-000000000004', 'dd000000-0004-4000-a000-000000000005', 'dd000000-0004-4000-a000-000000000006', 'dd000000-0004-4000-a000-000000000007', 'dd000000-0004-4000-a000-000000000008', 'dd000000-0004-4000-a000-000000000009', 'dd000000-0004-4000-a000-000000000010', 'dd000000-0004-4000-a000-000000000011', 'dd000000-0004-4000-a000-000000000012', 'dd000000-0005-4000-a000-000000000001', 'dd000000-0005-4000-a000-000000000002', 'dd000000-0006-4000-a000-000000000001', 'dd000000-0006-4000-a000-000000000002', 'dd000000-0006-4000-a000-000000000003', 'dd000000-0006-4000-a000-000000000004', 'dd000000-0006-4000-a000-000000000005', 'dd000000-0006-4000-a000-000000000006');
INSERT INTO laps (session_id, lap_number, lap_time_ms) VALUES
('dd000000-0001-4000-a000-000000000001', 1, 92100),
('dd000000-0001-4000-a000-000000000001', 2, 91900),
('dd000000-0001-4000-a000-000000000001', 3, 92200),
('dd000000-0001-4000-a000-000000000001', 4, 92000),
('dd000000-0001-4000-a000-000000000001', 5, 92150),
('dd000000-0001-4000-a000-000000000001', 6, 91950),
('dd000000-0001-4000-a000-000000000001', 7, 92250),
('dd000000-0001-4000-a000-000000000001', 8, 92050),
('dd000000-0001-4000-a000-000000000002', 1, 92000),
('dd000000-0001-4000-a000-000000000002', 2, 91600),
('dd000000-0001-4000-a000-000000000002', 3, 92300),
('dd000000-0001-4000-a000-000000000002', 4, 91700),
('dd000000-0001-4000-a000-000000000002', 5, 92200),
('dd000000-0001-4000-a000-000000000002', 6, 91500),
('dd000000-0001-4000-a000-000000000002', 7, 92400),
('dd000000-0001-4000-a000-000000000002', 8, 91800),
('dd000000-0001-4000-a000-000000000003', 1, 91900),
('dd000000-0001-4000-a000-000000000003', 2, 91400),
('dd000000-0001-4000-a000-000000000003', 3, 92500),
('dd000000-0001-4000-a000-000000000003', 4, 91500),
('dd000000-0001-4000-a000-000000000003', 5, 92300),
('dd000000-0001-4000-a000-000000000003', 6, 91400),
('dd000000-0001-4000-a000-000000000003', 7, 92600),
('dd000000-0001-4000-a000-000000000003', 8, 91600),
('dd000000-0001-4000-a000-000000000004', 1, 92050),
('dd000000-0001-4000-a000-000000000004', 2, 91750),
('dd000000-0001-4000-a000-000000000004', 3, 92150),
('dd000000-0001-4000-a000-000000000004', 4, 91800),
('dd000000-0001-4000-a000-000000000004', 5, 92000),
('dd000000-0001-4000-a000-000000000004', 6, 91700),
('dd000000-0001-4000-a000-000000000004', 7, 92200),
('dd000000-0001-4000-a000-000000000004', 8, 91850),
('dd000000-0001-4000-a000-000000000005', 1, 91950),
('dd000000-0001-4000-a000-000000000005', 2, 91500),
('dd000000-0001-4000-a000-000000000005', 3, 92150),
('dd000000-0001-4000-a000-000000000005', 4, 91600),
('dd000000-0001-4000-a000-000000000005', 5, 92050),
('dd000000-0001-4000-a000-000000000005', 6, 91450),
('dd000000-0001-4000-a000-000000000005', 7, 92250),
('dd000000-0001-4000-a000-000000000005', 8, 91700),
('dd000000-0001-4000-a000-000000000006', 1, 91850),
('dd000000-0001-4000-a000-000000000006', 2, 91650),
('dd000000-0001-4000-a000-000000000006', 3, 91950),
('dd000000-0001-4000-a000-000000000006', 4, 91700),
('dd000000-0001-4000-a000-000000000006', 5, 91900),
('dd000000-0001-4000-a000-000000000006', 6, 91600),
('dd000000-0001-4000-a000-000000000006', 7, 92000),
('dd000000-0001-4000-a000-000000000006', 8, 91750),
('dd000000-0001-4000-a000-000000000007', 1, 91800),
('dd000000-0001-4000-a000-000000000007', 2, 91350),
('dd000000-0001-4000-a000-000000000007', 3, 92100),
('dd000000-0001-4000-a000-000000000007', 4, 91450),
('dd000000-0001-4000-a000-000000000007', 5, 92000),
('dd000000-0001-4000-a000-000000000007', 6, 91300),
('dd000000-0001-4000-a000-000000000007', 7, 92200),
('dd000000-0001-4000-a000-000000000007', 8, 91550),
('dd000000-0001-4000-a000-000000000008', 1, 91300),
('dd000000-0001-4000-a000-000000000008', 2, 91500),
('dd000000-0001-4000-a000-000000000008', 3, 91400),
('dd000000-0001-4000-a000-000000000008', 4, 91600),
('dd000000-0001-4000-a000-000000000008', 5, 91700),
('dd000000-0001-4000-a000-000000000008', 6, 91800),
('dd000000-0001-4000-a000-000000000008', 7, 92000),
('dd000000-0001-4000-a000-000000000008', 8, 92150),
('dd000000-0001-4000-a000-000000000008', 9, 92200),
('dd000000-0002-4000-a000-000000000001', 1, 90100),
('dd000000-0002-4000-a000-000000000001', 2, 89800),
('dd000000-0002-4000-a000-000000000001', 3, 89400),
('dd000000-0002-4000-a000-000000000001', 4, 90000),
('dd000000-0002-4000-a000-000000000001', 5, 89900),
('dd000000-0002-4000-a000-000000000001', 6, 89700),
('dd000000-0002-4000-a000-000000000001', 7, 90200),
('dd000000-0002-4000-a000-000000000001', 8, 89600),
('dd000000-0002-4000-a000-000000000002', 1, 90800),
('dd000000-0002-4000-a000-000000000002', 2, 90600),
('dd000000-0002-4000-a000-000000000002', 3, 90500),
('dd000000-0002-4000-a000-000000000002', 4, 90900),
('dd000000-0002-4000-a000-000000000002', 5, 90700),
('dd000000-0002-4000-a000-000000000002', 6, 91000),
('dd000000-0002-4000-a000-000000000002', 7, 90600),
('dd000000-0002-4000-a000-000000000002', 8, 90800),
('dd000000-0002-4000-a000-000000000003', 1, 90900),
('dd000000-0002-4000-a000-000000000003', 2, 90700),
('dd000000-0002-4000-a000-000000000003', 3, 90600),
('dd000000-0002-4000-a000-000000000003', 4, 91000),
('dd000000-0002-4000-a000-000000000003', 5, 90800),
('dd000000-0002-4000-a000-000000000003', 6, 91100),
('dd000000-0002-4000-a000-000000000003', 7, 90700),
('dd000000-0002-4000-a000-000000000003', 8, 90900),
('dd000000-0003-4000-a000-000000000001', 1, 95250),
('dd000000-0003-4000-a000-000000000001', 2, 95750),
('dd000000-0003-4000-a000-000000000001', 3, 95300),
('dd000000-0003-4000-a000-000000000001', 4, 95700),
('dd000000-0003-4000-a000-000000000001', 5, 95350),
('dd000000-0003-4000-a000-000000000001', 6, 95650),
('dd000000-0003-4000-a000-000000000001', 7, 95400),
('dd000000-0003-4000-a000-000000000001', 8, 95600),
('dd000000-0003-4000-a000-000000000002', 1, 95200),
('dd000000-0003-4000-a000-000000000002', 2, 95700),
('dd000000-0003-4000-a000-000000000002', 3, 95250),
('dd000000-0003-4000-a000-000000000002', 4, 95650),
('dd000000-0003-4000-a000-000000000002', 5, 95300),
('dd000000-0003-4000-a000-000000000002', 6, 95600),
('dd000000-0003-4000-a000-000000000002', 7, 95350),
('dd000000-0003-4000-a000-000000000002', 8, 95550),
('dd000000-0003-4000-a000-000000000003', 1, 95300),
('dd000000-0003-4000-a000-000000000003', 2, 95800),
('dd000000-0003-4000-a000-000000000003', 3, 95350),
('dd000000-0003-4000-a000-000000000003', 4, 95750),
('dd000000-0003-4000-a000-000000000003', 5, 95400),
('dd000000-0003-4000-a000-000000000003', 6, 95700),
('dd000000-0003-4000-a000-000000000003', 7, 95450),
('dd000000-0003-4000-a000-000000000003', 8, 95650),
('dd000000-0003-4000-a000-000000000004', 1, 95150),
('dd000000-0003-4000-a000-000000000004', 2, 95650),
('dd000000-0003-4000-a000-000000000004', 3, 95200),
('dd000000-0003-4000-a000-000000000004', 4, 95600),
('dd000000-0003-4000-a000-000000000004', 5, 95250),
('dd000000-0003-4000-a000-000000000004', 6, 95550),
('dd000000-0003-4000-a000-000000000004', 7, 95300),
('dd000000-0003-4000-a000-000000000004', 8, 95500),
('dd000000-0003-4000-a000-000000000005', 1, 94800),
('dd000000-0003-4000-a000-000000000005', 2, 96400),
('dd000000-0003-4000-a000-000000000005', 3, 95100),
('dd000000-0003-4000-a000-000000000005', 4, 96200),
('dd000000-0003-4000-a000-000000000005', 5, 94900),
('dd000000-0003-4000-a000-000000000005', 6, 96400),
('dd000000-0003-4000-a000-000000000005', 7, 94900),
('dd000000-0003-4000-a000-000000000005', 8, 95100),
('dd000000-0004-4000-a000-000000000001', 1, 90100),
('dd000000-0004-4000-a000-000000000001', 2, 89500),
('dd000000-0004-4000-a000-000000000001', 3, 90300),
('dd000000-0004-4000-a000-000000000001', 4, 89600),
('dd000000-0004-4000-a000-000000000001', 5, 90000),
('dd000000-0004-4000-a000-000000000001', 6, 89400),
('dd000000-0004-4000-a000-000000000001', 7, 90400),
('dd000000-0004-4000-a000-000000000001', 8, 89700),
('dd000000-0004-4000-a000-000000000002', 1, 89950),
('dd000000-0004-4000-a000-000000000002', 2, 89300),
('dd000000-0004-4000-a000-000000000002', 3, 90200),
('dd000000-0004-4000-a000-000000000002', 4, 89400),
('dd000000-0004-4000-a000-000000000002', 5, 89850),
('dd000000-0004-4000-a000-000000000002', 6, 89150),
('dd000000-0004-4000-a000-000000000002', 7, 90300),
('dd000000-0004-4000-a000-000000000002', 8, 89500),
('dd000000-0004-4000-a000-000000000003', 1, 89500),
('dd000000-0004-4000-a000-000000000003', 2, 89000),
('dd000000-0004-4000-a000-000000000003', 3, 89700),
('dd000000-0004-4000-a000-000000000003', 4, 89050),
('dd000000-0004-4000-a000-000000000003', 5, 89450),
('dd000000-0004-4000-a000-000000000003', 6, 88900),
('dd000000-0004-4000-a000-000000000003', 7, 89750),
('dd000000-0004-4000-a000-000000000003', 8, 89150),
('dd000000-0004-4000-a000-000000000004', 1, 89400),
('dd000000-0004-4000-a000-000000000004', 2, 88800),
('dd000000-0004-4000-a000-000000000004', 3, 89600),
('dd000000-0004-4000-a000-000000000004', 4, 88900),
('dd000000-0004-4000-a000-000000000004', 5, 89300),
('dd000000-0004-4000-a000-000000000004', 6, 88700),
('dd000000-0004-4000-a000-000000000004', 7, 89700),
('dd000000-0004-4000-a000-000000000004', 8, 88950),
('dd000000-0004-4000-a000-000000000005', 1, 89150),
('dd000000-0004-4000-a000-000000000005', 2, 88550),
('dd000000-0004-4000-a000-000000000005', 3, 89350),
('dd000000-0004-4000-a000-000000000005', 4, 88650),
('dd000000-0004-4000-a000-000000000005', 5, 89050),
('dd000000-0004-4000-a000-000000000005', 6, 88450),
('dd000000-0004-4000-a000-000000000005', 7, 89450),
('dd000000-0004-4000-a000-000000000005', 8, 88750),
('dd000000-0004-4000-a000-000000000006', 1, 88900),
('dd000000-0004-4000-a000-000000000006', 2, 88300),
('dd000000-0004-4000-a000-000000000006', 3, 89100),
('dd000000-0004-4000-a000-000000000006', 4, 88400),
('dd000000-0004-4000-a000-000000000006', 5, 88800),
('dd000000-0004-4000-a000-000000000006', 6, 88200),
('dd000000-0004-4000-a000-000000000006', 7, 89200),
('dd000000-0004-4000-a000-000000000006', 8, 88500),
('dd000000-0004-4000-a000-000000000007', 1, 88600),
('dd000000-0004-4000-a000-000000000007', 2, 88100),
('dd000000-0004-4000-a000-000000000007', 3, 88800),
('dd000000-0004-4000-a000-000000000007', 4, 88150),
('dd000000-0004-4000-a000-000000000007', 5, 88550),
('dd000000-0004-4000-a000-000000000007', 6, 88000),
('dd000000-0004-4000-a000-000000000007', 7, 88850),
('dd000000-0004-4000-a000-000000000007', 8, 88250),
('dd000000-0004-4000-a000-000000000008', 1, 88550),
('dd000000-0004-4000-a000-000000000008', 2, 87900),
('dd000000-0004-4000-a000-000000000008', 3, 88800),
('dd000000-0004-4000-a000-000000000008', 4, 88000),
('dd000000-0004-4000-a000-000000000008', 5, 88450),
('dd000000-0004-4000-a000-000000000008', 6, 87750),
('dd000000-0004-4000-a000-000000000008', 7, 88900),
('dd000000-0004-4000-a000-000000000008', 8, 88100),
('dd000000-0004-4000-a000-000000000009', 1, 88200),
('dd000000-0004-4000-a000-000000000009', 2, 87600),
('dd000000-0004-4000-a000-000000000009', 3, 88400),
('dd000000-0004-4000-a000-000000000009', 4, 87700),
('dd000000-0004-4000-a000-000000000009', 5, 88100),
('dd000000-0004-4000-a000-000000000009', 6, 87500),
('dd000000-0004-4000-a000-000000000009', 7, 88500),
('dd000000-0004-4000-a000-000000000009', 8, 87800),
('dd000000-0004-4000-a000-000000000010', 1, 87850),
('dd000000-0004-4000-a000-000000000010', 2, 87350),
('dd000000-0004-4000-a000-000000000010', 3, 88050),
('dd000000-0004-4000-a000-000000000010', 4, 87400),
('dd000000-0004-4000-a000-000000000010', 5, 87800),
('dd000000-0004-4000-a000-000000000010', 6, 87250),
('dd000000-0004-4000-a000-000000000010', 7, 88100),
('dd000000-0004-4000-a000-000000000010', 8, 87500),
('dd000000-0004-4000-a000-000000000011', 1, 87700),
('dd000000-0004-4000-a000-000000000011', 2, 87100),
('dd000000-0004-4000-a000-000000000011', 3, 87900),
('dd000000-0004-4000-a000-000000000011', 4, 87200),
('dd000000-0004-4000-a000-000000000011', 5, 87600),
('dd000000-0004-4000-a000-000000000011', 6, 87000),
('dd000000-0004-4000-a000-000000000011', 7, 88000),
('dd000000-0004-4000-a000-000000000011', 8, 87300),
('dd000000-0004-4000-a000-000000000012', 1, 87160),
('dd000000-0004-4000-a000-000000000012', 2, 86770),
('dd000000-0004-4000-a000-000000000012', 3, 87300),
('dd000000-0004-4000-a000-000000000012', 4, 86830),
('dd000000-0004-4000-a000-000000000012', 5, 87100),
('dd000000-0004-4000-a000-000000000012', 6, 86700),
('dd000000-0004-4000-a000-000000000012', 7, 87360),
('dd000000-0004-4000-a000-000000000012', 8, 86900),
('dd000000-0005-4000-a000-000000000001', 1, 98500),
('dd000000-0005-4000-a000-000000000001', 2, 97800),
('dd000000-0005-4000-a000-000000000001', 3, 98200),
('dd000000-0005-4000-a000-000000000001', 4, 97600),
('dd000000-0005-4000-a000-000000000001', 5, 98000),
('dd000000-0005-4000-a000-000000000002', 1, 97900),
('dd000000-0005-4000-a000-000000000002', 2, 97400),
('dd000000-0005-4000-a000-000000000002', 3, 97700),
('dd000000-0005-4000-a000-000000000002', 4, 97500),
('dd000000-0006-4000-a000-000000000001', 1, 90500),
('dd000000-0006-4000-a000-000000000001', 2, 90250),
('dd000000-0006-4000-a000-000000000001', 3, 90600),
('dd000000-0006-4000-a000-000000000001', 4, 90150),
('dd000000-0006-4000-a000-000000000001', 5, 90650),
('dd000000-0006-4000-a000-000000000001', 6, 90200),
('dd000000-0006-4000-a000-000000000001', 7, 90550),
('dd000000-0006-4000-a000-000000000001', 8, 90300),
('dd000000-0006-4000-a000-000000000002', 1, 90400),
('dd000000-0006-4000-a000-000000000002', 2, 90050),
('dd000000-0006-4000-a000-000000000002', 3, 90450),
('dd000000-0006-4000-a000-000000000002', 4, 89900),
('dd000000-0006-4000-a000-000000000002', 5, 90600),
('dd000000-0006-4000-a000-000000000002', 6, 90050),
('dd000000-0006-4000-a000-000000000002', 7, 90450),
('dd000000-0006-4000-a000-000000000002', 8, 90100),
('dd000000-0006-4000-a000-000000000003', 1, 90500),
('dd000000-0006-4000-a000-000000000003', 2, 90150),
('dd000000-0006-4000-a000-000000000003', 3, 90700),
('dd000000-0006-4000-a000-000000000003', 4, 90000),
('dd000000-0006-4000-a000-000000000003', 5, 90800),
('dd000000-0006-4000-a000-000000000003', 6, 90100),
('dd000000-0006-4000-a000-000000000003', 7, 90650),
('dd000000-0006-4000-a000-000000000003', 8, 90300),
('dd000000-0006-4000-a000-000000000004', 1, 90500),
('dd000000-0006-4000-a000-000000000004', 2, 90100),
('dd000000-0006-4000-a000-000000000004', 3, 90750),
('dd000000-0006-4000-a000-000000000004', 4, 89950),
('dd000000-0006-4000-a000-000000000004', 5, 90850),
('dd000000-0006-4000-a000-000000000004', 6, 90050),
('dd000000-0006-4000-a000-000000000004', 7, 90700),
('dd000000-0006-4000-a000-000000000004', 8, 90300),
('dd000000-0006-4000-a000-000000000005', 1, 90600),
('dd000000-0006-4000-a000-000000000005', 2, 90200),
('dd000000-0006-4000-a000-000000000005', 3, 90900),
('dd000000-0006-4000-a000-000000000005', 4, 89950),
('dd000000-0006-4000-a000-000000000005', 5, 91050),
('dd000000-0006-4000-a000-000000000005', 6, 90100),
('dd000000-0006-4000-a000-000000000005', 7, 90800),
('dd000000-0006-4000-a000-000000000005', 8, 90400),
('dd000000-0006-4000-a000-000000000006', 1, 90650),
('dd000000-0006-4000-a000-000000000006', 2, 90150),
('dd000000-0006-4000-a000-000000000006', 3, 90850),
('dd000000-0006-4000-a000-000000000006', 4, 90200),
('dd000000-0006-4000-a000-000000000006', 5, 90750),
('dd000000-0006-4000-a000-000000000006', 6, 90150),
('dd000000-0006-4000-a000-000000000006', 7, 90950),
('dd000000-0006-4000-a000-000000000006', 8, 90300);
COMMIT;
