// Usage: npx tsx scripts/seed/generate-demo-seed.ts --coach-email=<email> [--out=path]
// Verifies every scenario against the real analytics before emitting SQL.
// Run from web/.
import { writeFileSync } from 'fs';
import { join } from 'path';
import { evaluateStudent } from '../../src/lib/analytics-v2';
import { SCENARIOS, toStudentHistory, weekendDate, type Scenario } from './demo-scenarios';

export function driverUuid(n: number): string {
  return `dd000000-0000-4000-a000-${String(n).padStart(12, '0')}`;
}
export function sessionUuid(driverN: number, sessionN: number): string {
  return `dd000000-${String(driverN).padStart(4, '0')}-4000-a000-${String(sessionN).padStart(12, '0')}`;
}

const q = (s: string) => s.replace(/'/g, "''");

/** Verify all scenarios trip exactly their expected flags. Throws with a diff on mismatch. */
export function verifyScenarios(scenarios: Scenario[], now: Date): string[] {
  const report: string[] = [];
  const failures: string[] = [];
  for (const s of scenarios) {
    const r = evaluateStudent(toStudentHistory(s, now));
    const actual = r.flags.map(f => f.kind).sort();
    const expected = [...s.expect.flagKinds].sort();
    const ok =
      JSON.stringify(actual) === JSON.stringify(expected) &&
      r.baselineState === s.expect.baselineState &&
      r.ready === s.expect.ready &&
      (s.expect.sustained === undefined || r.flags[0]?.sustained === s.expect.sustained);
    const state = expected.length ? expected.join('+') : s.expect.ready ? 'ready' : s.expect.baselineState === 'building' ? 'building' : 'quiet';
    if (ok) {
      report.push(`  ${s.name} -> ${state} \u2713`);
    } else {
      failures.push(
        `  ${s.name}: expected flags=[${expected}] baseline=${s.expect.baselineState} ready=${s.expect.ready}` +
        ` | actual flags=[${actual}] baseline=${r.baselineState} ready=${r.ready} sustained=${r.flags[0]?.sustained}`,
      );
    }
  }
  if (failures.length) {
    throw new Error(`Scenario verification FAILED — nothing emitted:\n${failures.join('\n')}`);
  }
  return report;
}

export function buildSeedSql(scenarios: Scenario[], coachEmail: string, now: Date): string {
  const trackNames = [...new Set(scenarios.flatMap(s => s.sessions.map(x => x.trackName)))];
  const coach = `(SELECT id FROM coaches WHERE email = '${q(coachEmail)}')`;
  const lines: string[] = [];

  lines.push(`BEGIN;`);
  lines.push(`-- demo-seed.sql — GENERATED by scripts/seed/generate-demo-seed.ts`);
  lines.push(`-- Generated: ${now.toISOString()}  Coach: ${coachEmail}`);
  lines.push(`-- Idempotent: re-run any time to refresh demo dates. Do not edit by hand.`);

  // Guards: coach and tracks must exist.
  lines.push(`DO $$ BEGIN`);
  lines.push(`  IF NOT EXISTS (SELECT 1 FROM coaches WHERE email = '${q(coachEmail)}') THEN`);
  lines.push(`    RAISE EXCEPTION 'Coach % not found — check coaches.email', '${q(coachEmail)}';`);
  lines.push(`  END IF;`);
  for (const t of trackNames) {
    lines.push(`  IF NOT EXISTS (SELECT 1 FROM tracks WHERE name = '${q(t)}') THEN`);
    lines.push(`    RAISE EXCEPTION 'Track % not found — check tracks.name', '${q(t)}';`);
    lines.push(`  END IF;`);
  }
  lines.push(`END $$;`);

  const allSessionIds: string[] = [];

  for (const s of scenarios) {
    const dId = driverUuid(s.n);
    lines.push(``);
    lines.push(`-- ${s.name} (${s.expect.flagKinds.join('+') || (s.expect.ready ? 'ready' : s.expect.baselineState)})`);
    lines.push(
      `INSERT INTO drivers (id, name, email, coach_id, created_at) VALUES ` +
      `('${dId}', '${q(s.name)}', '${q(s.email)}', ${coach}, now()) ` +
      `ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, coach_id = EXCLUDED.coach_id;`,
    );
    lines.push(
      `INSERT INTO driver_profiles (driver_id, experience_level, total_sessions) VALUES ` +
      `('${dId}', '${s.experienceLevel}', ${s.sessions.length}) ` +
      `ON CONFLICT (driver_id) DO UPDATE SET experience_level = EXCLUDED.experience_level, total_sessions = EXCLUDED.total_sessions;`,
    );
    s.sessions.forEach((sess, i) => {
      const sId = sessionUuid(s.n, i + 1);
      allSessionIds.push(sId);
      const date = weekendDate(now, sess.weeksAgo, sess.day);
      const total = sess.lapTimesMs.reduce((a, b) => a + b, 0);
      const best = Math.min(...sess.lapTimesMs);
      lines.push(
        `INSERT INTO sessions (id, driver_id, track_id, date, total_time_ms, best_lap_ms, source) VALUES ` +
        `('${sId}', '${dId}', (SELECT id FROM tracks WHERE name = '${q(sess.trackName)}'), '${date}', ${total}, ${best}, 'manual') ` +
        `ON CONFLICT (id) DO UPDATE SET driver_id = EXCLUDED.driver_id, track_id = EXCLUDED.track_id, ` +
        `date = EXCLUDED.date, total_time_ms = EXCLUDED.total_time_ms, best_lap_ms = EXCLUDED.best_lap_ms;`,
      );
    });
  }

  // Refresh laps wholesale: delete-then-insert is simpler than per-lap upserts and
  // handles scenarios shrinking between generator versions.
  lines.push(``);
  lines.push(`DELETE FROM laps WHERE session_id IN (${allSessionIds.map(id => `'${id}'`).join(', ')});`);
  const lapValues: string[] = [];
  for (const s of scenarios) {
    s.sessions.forEach((sess, i) => {
      const sId = sessionUuid(s.n, i + 1);
      sess.lapTimesMs.forEach((t, lapIdx) => {
        lapValues.push(`('${sId}', ${lapIdx + 1}, ${t})`);
      });
    });
  }
  lines.push(`INSERT INTO laps (session_id, lap_number, lap_time_ms) VALUES`);
  lines.push(lapValues.join(',\n') + ';');
  lines.push(`COMMIT;`);
  return lines.join('\n') + '\n';
}

function main() {
  const args = Object.fromEntries(
    process.argv.slice(2).filter(a => a.startsWith('--')).map(a => a.slice(2).split('=') as [string, string]),
  );
  const coachEmail = args['coach-email'];
  if (!coachEmail) {
    console.error('Usage: npx tsx scripts/seed/generate-demo-seed.ts --coach-email=<email> [--out=path]');
    process.exit(1);
  }
  const now = new Date();
  const report = verifyScenarios(SCENARIOS, now);
  console.log('Scenario verification:');
  for (const line of report) console.log(line);
  const out = args['out'] ?? join(__dirname, 'demo-seed.sql');
  writeFileSync(out, buildSeedSql(SCENARIOS, coachEmail, now));
  console.log(`\nWrote ${out}`);
}

if (require.main === module) main();
